name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Kjører daglig
  workflow_dispatch:     # Kan også kjøre manuelt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit & Push Snake
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "your-email@example.com"
          git add dist/*.svg
          git commit -m "Update Snake"
          git push
