name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Sjekk ut repo
      - uses: actions/checkout@v3

      # Lag mappen dist hvis den ikke finnes
      - name: Make dist folder
        run: mkdir -p dist

      # Generer Snake SVG
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Commit og push filene
      - name: Commit and push Snake
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "dilbrinha@gmail.com"
          git add dist/*.svg
          git commit -m "Update Snake" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
